// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDilYAmGBP5bte7XlyVIzi9iemEhL40qu0',
    appId: '1:1069980191359:web:488bd1e9d5976668ef4d4a',
    messagingSenderId: '1069980191359',
    projectId: 'blood-bank1234',
    authDomain: 'blood-bank1234.firebaseapp.com',
    storageBucket: 'blood-bank1234.firebasestorage.app',
    measurementId: 'G-Z262THM6MC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqy_Ekqrwqwp-QgR7VZne6eLCz3Kj6N-g',
    appId: '1:1069980191359:android:995e079ab3c09a90ef4d4a',
    messagingSenderId: '1069980191359',
    projectId: 'blood-bank1234',
    storageBucket: 'blood-bank1234.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDskyCCCRhWhlCUNOAdGUPELUMyILjRZW0',
    appId: '1:1069980191359:ios:8a8ebb13b519120fef4d4a',
    messagingSenderId: '1069980191359',
    projectId: 'blood-bank1234',
    storageBucket: 'blood-bank1234.firebasestorage.app',
    iosBundleId: 'com.example.bloodBank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDskyCCCRhWhlCUNOAdGUPELUMyILjRZW0',
    appId: '1:1069980191359:ios:8a8ebb13b519120fef4d4a',
    messagingSenderId: '1069980191359',
    projectId: 'blood-bank1234',
    storageBucket: 'blood-bank1234.firebasestorage.app',
    iosBundleId: 'com.example.bloodBank',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDilYAmGBP5bte7XlyVIzi9iemEhL40qu0',
    appId: '1:1069980191359:web:a54c3ddb00bf7da2ef4d4a',
    messagingSenderId: '1069980191359',
    projectId: 'blood-bank1234',
    authDomain: 'blood-bank1234.firebaseapp.com',
    storageBucket: 'blood-bank1234.firebasestorage.app',
    measurementId: 'G-Y688FH0ECM',
  );
}
